### ISSUE TITLE
Possible suggestion to handle the hierarchy of the character

### ISSUE THREAD

**Issue by dogboy357** [nowlenaustin/DnD-Character-Creator#1]
It came to me just now, to simplify the character could we build the overall character as a base object with vars: name, age, player name, total xp, physical traits, etc.

You could then do more objects for each character class as that extends character, each with its own set variables (like the modifiers for the base stats)

**Comment by nowlenaustin** [comment]
Yeah I was thinking about that last time I worked on it. We're at a point where it's not too hard to implement it. I'll take a look at making the changes need to switch it over to using the character class. We just need a method in the character class that we can call to create the PDF.

**Comment by nowlenaustin** [comment]
Also we need to make asset files (txt files most likely) for each character class and race with special attributes that come with each race and class (e.g. special feats and spells and stuff).

**Comment by nowlenaustin** [comment]
Completed! There is now a class called characterData which holds the user created character information in public variables and contains a method to create the pdf from that stored information.
